name: Pypi
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Release main branch to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
