name: Simulation Test
on:
  push:
    branches-ignore:
      - "master"

jobs:
  train-mnist-classifier:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        torch-version: ["1.9.0", "1.10.0", "1.11.0"]
        include:
          - python-version: "3.10"
            torch-version: "1.11.0"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install torch==${{ matrix.torch-version }}
          pip install -r requirements.txt
          pip install -r requirements_util.txt
          python init.py

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run Simulation
        run: python test/simulate/simulate_train_mnist_cla.py

  train-mnist-gan:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]
        torch-version: [ "1.9.0", "1.10.0", "1.11.0" ]
        include:
          - python-version: "3.10"
            torch-version: "1.11.0"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install torch==${{ matrix.torch-version }}
          pip install -r requirements.txt
          pip install -r requirements_util.txt
          python init.py

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run Simulation
        run: python test/simulate/simulate_train_mnist_gan.py
